server {
    listen 4232;
    server_name localhost;
    host 127.0.0.1;
    client_max_size 10000;

	location / {
		root /www/html;
		index index.html;
		allowed GET POST HEAD;
		cgi .py /bin/create_file.py;
		autoindex false;
	}

    location /get {
        root /www/html;
        index get.html;
        allowed GET;
        autoindex false;
    }
    location /post {
        root /www/html;
        index post.html;
        allowed GET POST;
		cgi .py ./bin/create_file.py;
        autoindex false;
    }

	location /create_file.py {
        allowed GET POST;
        cgi .py ./bin/create_file.py;
	}

    location /delete {
        root /www/html;
        index delete.html;
        allowed GET DELETE;
        cgi .py ./bin/delete_file.py;
        autoindex false;
    }

	location /delete_file.py {
        allowed GET DELETE;
        cgi .py ./bin/delete_file.py;
    }

    location /put {
        root /www/html;
        index put.html;
        allowed GET PUT;
        autoindex false;
    }

	location /put_file.py {
        allowed GET DELETE;
        cgi .py ./bin/put_file.py;
    }

    location /head {
        root /www/html;
        index head.html;
        allowed GET HEAD;
        autoindex false;
    }

    location /options {
        root /www/html;
        index options.html;
        allowed GET OPTIONS;
        autoindex false;
    }

    location /trace {
        root /www/html;
        index trace.html;
        allowed GET TRACE;
        autoindex false;
    }

    location /patch {
        root /www/html;
        index patch.html;
        allowed GET PATCH;
        autoindex false;
    }

    location /connect {
        root /www/html;
        index connect.html;
        allowed GET CONNECT;
        autoindex false;
    }


	location /files {
        root /www/html;
        index delete.html;
        allowed GET POST DELETE;
        autoindex false;
    }
}