server {
	listen 8080;
	host 127.0.0.1;
	server_name localhost;
	client_max_size 10000;

	location / {
		root /www/html;
		index index.html;
		allowed GET;
		autoindex false;
	}

	location /images {
		root /www/images;
		index img.html;
		allowed GET POST;
		autoindex false;
	}

	location /users {
		root /www/users;
		index login.html;
		allowed DELETE;
		autoindex false;
	}

	location /client {
		root /www/clients;
		index login.html;
		allowed DELETE;
		autoindex false;
	}

}



server {
	listen 8081;
	host 127.0.0.2;
	server_name local;
	client_max_size 10000;

	location / {
		root /www/html;
		index index.html;
		allowed GET;
		autoindex false;
	}

	location /images {
		root /www/images;
		index img.html;
		allowed GET POST;
		autoindex false;
	}

	location /users {
		root /www/users;
		index login.html;
		allowed DELETE;
		autoindex false;
	}
}